name: Juice-Shop-Test-Pipeline

on: [push] # Sen her kod attığında çalış demek

jobs:
  guvenlik-taramasi:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 1- Gitleaks (Sifre Kontrolü)
        uses: gitleaks/gitleaks-action@v2

      - name: 2- Semgrep (Kod Hatasi)
        run: |
          python3 -m pip install semgrep
          semgrep --config auto .

      - name: 3- Syft (Liste Yapma)
        uses: anchore/sbom-action@v0

      - name: 4- Docker Build
        run: docker build .
